### ISSUE TITLE
Integrating into Paymill website

### ISSUE THREAD

**Issue by d0mme-zz** [rainboxx/Paymill-REST#1]
Just let it me know when this repo can be integrated into our website.

Best,
Dom

**Comment by rainboxx** [comment]
Documentation is now finished, the wrapper is live.  See it here: https://metacpan.org/pod/Paymill::REST

To download and install, run: `cpanm Paymill::REST`
Run the following when you don't have `cpanm` installed: `cpan install Paymill::REST`
